import streamlit as st

def app():
    st.title("Sentiment Analysis Dashboard")
    st.header("Private Universities in Jabodetabek")
    st.write("")
    st.write("If you’re prospective college students, then, this dashboard is for you!")
    st.write("You may search your desired Private University in Jabodetabek to compare one each other. ")
    st.write("Need to declare that the source data of this sentiment analysis comes from Twitter, so it’s based on Netizen’s comment, story from friend to friend, and might be their experience. The data is not limited by only show Netizen’s own tweet, but it could be Re-Tweet, Quote Re-Tweet, or maybe bot’s tweet.")
    st.write("Here are the description for the menus:")
    st.subheader("1. Home")
    st.write("Welcoming page and informations about the web")
    st.subheader("2. Search Entry")
    st.write("- You may search the university name here. How to: ")
    st.write("- Type “Gundar” in text-box")
    st.write("- Choose until what date you want to see the source tweets")
    st.write("- Click “Analyze” button")
    st.write("- After the result is generated, you may save the file by clicking “Export the result” button")
    st.subheader("3. Upload File")
    st.write("If you have the file by your own, then you may upload it here. With the format CSV file and:")
    st.write("Column 1: “no”")
    st.write("Column 2: “tweets” which contains of cleaned tweets ")
    st.write("The steps are: ")
    st.write("- Click “Choose File” button")
    st.write("- Choose the file on your local directory")
    st.write("- Click “Analyze” button")
    st.write("- And the results will showed up. If you want to save the results, please click “Export the result” button")
    st.subheader("4. History")
    st.write("You may see the history searched keywords and its results")
    st.write("It won't show the uploaded file")